# Generated by Django 4.0.4 on 2022-04-20 13:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='URL',
            fields=[
                ('code', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('long_url', models.TextField()),
                ('date_created', models.DateField(auto_now_add=True)),
                ('status', models.CharField(default='ACTIVE', max_length=200)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Redirect',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('count', models.IntegerField()),
                ('url', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='linksly.url')),
            ],
        ),
    ]
