# Generated by Django 4.0.4 on 2022-06-12 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('linksly', '0002_alter_url_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='url',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'ACTIVE'), ('OFFLINE', 'OFFLINE')], default='ACTIVE', max_length=200),
        ),
    ]
