# Generated by Django 4.0.4 on 2022-04-20 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='URL',
            fields=[
                ('code', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('long_url', models.TextField()),
                ('date_created', models.DateField(auto_now_add=True)),
                ('status', models.CharField(default='ACTIVE', max_length=200)),
            ],
        ),
    ]
