# Generated by Django 4.0.4 on 2022-04-20 13:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('linksly', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Redirect',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('count', models.IntegerField()),
                ('url', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='linksly.url')),
            ],
        ),
    ]
